package com.clps.vo;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cart generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "cart", catalog = "jpetStore")
public class Cart implements java.io.Serializable {

	private Integer id;
	private String itemid;
	private String signonid;
	private Integer quantity;

	public Cart() {
	}

	public Cart(String signonid,String itemid,Integer quantity) {
		this.itemid = itemid;
		this.signonid = signonid;
		this.quantity = quantity;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "itemid", length = 10)
	public String getItemid() {
		return this.itemid;
	}

	public void setItemid(String itemid) {
		this.itemid = itemid;
	}

	@Column(name = "signonid", length = 10)
	public String getSignonid() {
		return this.signonid;
	}

	public void setSignonid(String signonid) {
		this.signonid = signonid;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Override
	public String toString() {
		return "Cart [id=" + id + ", itemid=" + itemid + ", signonid="
				+ signonid + ", quantity=" + quantity + "]";
	}
	
}
