package com.clps.vo;

// Generated 2018-1-12 9:45:46 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Inventory generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "inventory", catalog = "jpetStore")
public class Inventory implements java.io.Serializable {

	private String itemid;
	private int qty;

	public Inventory() {
	}

	public Inventory(String itemid, int qty) {
		this.itemid = itemid;
		this.qty = qty;
	}

	@Id
	@Column(name = "itemid", unique = true, nullable = false, length = 10)
	public String getItemid() {
		return this.itemid;
	}

	public void setItemid(String itemid) {
		this.itemid = itemid;
	}

	@Column(name = "qty", nullable = false)
	public int getQty() {
		return this.qty;
	}

	public void setQty(int qty) {
		this.qty = qty;
	}

}
