package com.clps.vo;

// Generated 2018-1-12 9:45:46 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name = "orders", catalog = "jpetStore")
public class Orders implements java.io.Serializable {

	private int orderid;
	private String userid;
	private Date orderdate;
	private String shipaddr1;
	private String shipaddr2;
	private String shipcity;
	private String shipstate;
	private String shipzip;
	private String shipcountry;
	private String billaddr1;
	private String billaddr2;
	private String billcity;
	private String billstate;
	private String billzip;
	private String billcountry;
	private String courier;
	private BigDecimal totalprice;
	private String billtofirstname;
	private String billtolastname;
	private String shiptofirstname;
	private String shiptolastname;
	private String creditcard;
	private String exprdate;
	private String cardtype;
	private String locale;

	public Orders() {
	}

	public Orders(int orderid, String userid, Date orderdate, String shipaddr1,
			String shipcity, String shipstate, String shipzip,
			String shipcountry, String billaddr1, String billcity,
			String billstate, String billzip, String billcountry,
			String courier, BigDecimal totalprice, String billtofirstname,
			String billtolastname, String shiptofirstname,
			String shiptolastname, String creditcard, String exprdate,
			String cardtype, String locale) {
		this.orderid = orderid;
		this.userid = userid;
		this.orderdate = orderdate;
		this.shipaddr1 = shipaddr1;
		this.shipcity = shipcity;
		this.shipstate = shipstate;
		this.shipzip = shipzip;
		this.shipcountry = shipcountry;
		this.billaddr1 = billaddr1;
		this.billcity = billcity;
		this.billstate = billstate;
		this.billzip = billzip;
		this.billcountry = billcountry;
		this.courier = courier;
		this.totalprice = totalprice;
		this.billtofirstname = billtofirstname;
		this.billtolastname = billtolastname;
		this.shiptofirstname = shiptofirstname;
		this.shiptolastname = shiptolastname;
		this.creditcard = creditcard;
		this.exprdate = exprdate;
		this.cardtype = cardtype;
		this.locale = locale;
	}

	public Orders(int orderid, String userid, Date orderdate, String shipaddr1,
			String shipaddr2, String shipcity, String shipstate,
			String shipzip, String shipcountry, String billaddr1,
			String billaddr2, String billcity, String billstate,
			String billzip, String billcountry, String courier,
			BigDecimal totalprice, String billtofirstname,
			String billtolastname, String shiptofirstname,
			String shiptolastname, String creditcard, String exprdate,
			String cardtype, String locale) {
		this.orderid = orderid;
		this.userid = userid;
		this.orderdate = orderdate;
		this.shipaddr1 = shipaddr1;
		this.shipaddr2 = shipaddr2;
		this.shipcity = shipcity;
		this.shipstate = shipstate;
		this.shipzip = shipzip;
		this.shipcountry = shipcountry;
		this.billaddr1 = billaddr1;
		this.billaddr2 = billaddr2;
		this.billcity = billcity;
		this.billstate = billstate;
		this.billzip = billzip;
		this.billcountry = billcountry;
		this.courier = courier;
		this.totalprice = totalprice;
		this.billtofirstname = billtofirstname;
		this.billtolastname = billtolastname;
		this.shiptofirstname = shiptofirstname;
		this.shiptolastname = shiptolastname;
		this.creditcard = creditcard;
		this.exprdate = exprdate;
		this.cardtype = cardtype;
		this.locale = locale;
	}

	@Id
	@Column(name = "orderid", unique = true, nullable = false)
	public int getOrderid() {
		return this.orderid;
	}

	public void setOrderid(int orderid) {
		this.orderid = orderid;
	}

	@Column(name = "userid", nullable = false, length = 80)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "orderdate", nullable = false, length = 0)
	public Date getOrderdate() {
		return this.orderdate;
	}

	public void setOrderdate(Date orderdate) {
		this.orderdate = orderdate;
	}

	@Column(name = "shipaddr1", nullable = false, length = 80)
	public String getShipaddr1() {
		return this.shipaddr1;
	}

	public void setShipaddr1(String shipaddr1) {
		this.shipaddr1 = shipaddr1;
	}

	@Column(name = "shipaddr2", length = 80)
	public String getShipaddr2() {
		return this.shipaddr2;
	}

	public void setShipaddr2(String shipaddr2) {
		this.shipaddr2 = shipaddr2;
	}

	@Column(name = "shipcity", nullable = false, length = 80)
	public String getShipcity() {
		return this.shipcity;
	}

	public void setShipcity(String shipcity) {
		this.shipcity = shipcity;
	}

	@Column(name = "shipstate", nullable = false, length = 80)
	public String getShipstate() {
		return this.shipstate;
	}

	public void setShipstate(String shipstate) {
		this.shipstate = shipstate;
	}

	@Column(name = "shipzip", nullable = false, length = 20)
	public String getShipzip() {
		return this.shipzip;
	}

	public void setShipzip(String shipzip) {
		this.shipzip = shipzip;
	}

	@Column(name = "shipcountry", nullable = false, length = 20)
	public String getShipcountry() {
		return this.shipcountry;
	}

	public void setShipcountry(String shipcountry) {
		this.shipcountry = shipcountry;
	}

	@Column(name = "billaddr1", nullable = false, length = 80)
	public String getBilladdr1() {
		return this.billaddr1;
	}

	public void setBilladdr1(String billaddr1) {
		this.billaddr1 = billaddr1;
	}

	@Column(name = "billaddr2", length = 80)
	public String getBilladdr2() {
		return this.billaddr2;
	}

	public void setBilladdr2(String billaddr2) {
		this.billaddr2 = billaddr2;
	}

	@Column(name = "billcity", nullable = false, length = 80)
	public String getBillcity() {
		return this.billcity;
	}

	public void setBillcity(String billcity) {
		this.billcity = billcity;
	}

	@Column(name = "billstate", nullable = false, length = 80)
	public String getBillstate() {
		return this.billstate;
	}

	public void setBillstate(String billstate) {
		this.billstate = billstate;
	}

	@Column(name = "billzip", nullable = false, length = 20)
	public String getBillzip() {
		return this.billzip;
	}

	public void setBillzip(String billzip) {
		this.billzip = billzip;
	}

	@Column(name = "billcountry", nullable = false, length = 20)
	public String getBillcountry() {
		return this.billcountry;
	}

	public void setBillcountry(String billcountry) {
		this.billcountry = billcountry;
	}

	@Column(name = "courier", nullable = false, length = 80)
	public String getCourier() {
		return this.courier;
	}

	public void setCourier(String courier) {
		this.courier = courier;
	}

	@Column(name = "totalprice", nullable = false, precision = 10)
	public BigDecimal getTotalprice() {
		return this.totalprice;
	}

	public void setTotalprice(BigDecimal totalprice) {
		this.totalprice = totalprice;
	}

	@Column(name = "billtofirstname", nullable = false, length = 80)
	public String getBilltofirstname() {
		return this.billtofirstname;
	}

	public void setBilltofirstname(String billtofirstname) {
		this.billtofirstname = billtofirstname;
	}

	@Column(name = "billtolastname", nullable = false, length = 80)
	public String getBilltolastname() {
		return this.billtolastname;
	}

	public void setBilltolastname(String billtolastname) {
		this.billtolastname = billtolastname;
	}

	@Column(name = "shiptofirstname", nullable = false, length = 80)
	public String getShiptofirstname() {
		return this.shiptofirstname;
	}

	public void setShiptofirstname(String shiptofirstname) {
		this.shiptofirstname = shiptofirstname;
	}

	@Column(name = "shiptolastname", nullable = false, length = 80)
	public String getShiptolastname() {
		return this.shiptolastname;
	}

	public void setShiptolastname(String shiptolastname) {
		this.shiptolastname = shiptolastname;
	}

	@Column(name = "creditcard", nullable = false, length = 80)
	public String getCreditcard() {
		return this.creditcard;
	}

	public void setCreditcard(String creditcard) {
		this.creditcard = creditcard;
	}

	@Column(name = "exprdate", nullable = false, length = 7)
	public String getExprdate() {
		return this.exprdate;
	}

	public void setExprdate(String exprdate) {
		this.exprdate = exprdate;
	}

	@Column(name = "cardtype", nullable = false, length = 80)
	public String getCardtype() {
		return this.cardtype;
	}

	public void setCardtype(String cardtype) {
		this.cardtype = cardtype;
	}

	@Column(name = "locale", nullable = true, length = 80)
	public String getLocale() {
		return this.locale;
	}

	public void setLocale(String locale) {
		this.locale = locale;
	}

	@Override
	public String toString() {
		return "Orders [orderid=" + orderid + ", userid=" + userid
				+ ", orderdate=" + orderdate + ", shipaddr1=" + shipaddr1
				+ ", shipaddr2=" + shipaddr2 + ", shipcity=" + shipcity
				+ ", shipstate=" + shipstate + ", shipzip=" + shipzip
				+ ", shipcountry=" + shipcountry + ", billaddr1=" + billaddr1
				+ ", billaddr2=" + billaddr2 + ", billcity=" + billcity
				+ ", billstate=" + billstate + ", billzip=" + billzip
				+ ", billcountry=" + billcountry + ", courier=" + courier
				+ ", totalprice=" + totalprice + ", billtofirstname="
				+ billtofirstname + ", billtolastname=" + billtolastname
				+ ", shiptofirstname=" + shiptofirstname + ", shiptolastname="
				+ shiptolastname + ", creditcard=" + creditcard + ", exprdate="
				+ exprdate + ", cardtype=" + cardtype + ", locale=" + locale
				+ "]";
	}
	
}
