package com.clps.vo;

// Generated 2018-1-12 9:45:46 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Orderstatus generated by hbm2java
 */
@Entity
@Table(name = "orderstatus", catalog = "jpetStore")
public class Orderstatus implements java.io.Serializable {

	private OrderstatusId id;
	private Date timestamp;
	private String status;

	public Orderstatus() {
	}

	public Orderstatus(OrderstatusId id, String status) {
		this.id = id;
		this.status = status;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "orderid", column = @Column(name = "orderid", nullable = false)),
			@AttributeOverride(name = "linenum", column = @Column(name = "linenum", nullable = false)) })
	public OrderstatusId getId() {
		return this.id;
	}

	public void setId(OrderstatusId id) {
		this.id = id;
	}


	@Temporal(TemporalType.DATE)
	@Column(name = "timestamp", nullable = false, length = 0)
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	@Column(name = "status", nullable = false, length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
