package com.clps.vo;

// Generated 2018-1-12 9:45:46 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "product", catalog = "jpetStore")
public class Product implements java.io.Serializable {

	private String productid;
	private String category;
	private String name;
	private String descn;

	public Product() {
	}

	public Product(String productid, String category) {
		this.productid = productid;
		this.category = category;
	}

	public Product(String productid, String category, String name, String descn) {
		this.productid = productid;
		this.category = category;
		this.name = name;
		this.descn = descn;
	}

	@Id
	@Column(name = "productid", unique = true, nullable = false, length = 10)
	public String getProductid() {
		return this.productid;
	}

	public void setProductid(String productid) {
		this.productid = productid;
	}

	@Column(name = "category", nullable = false, length = 10)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "name", length = 80)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "descn")
	public String getDescn() {
		return this.descn;
	}

	public void setDescn(String descn) {
		this.descn = descn;
	}

	@Override
	public String toString() {
		return "Product [productid=" + productid + ", category=" + category
				+ ", name=" + name  + "]";
	}
}
