package com.clps.vo;

// Generated 2018-1-12 9:45:46 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Profile generated by hbm2java
 */
@Entity
@Table(name = "profile", catalog = "jpetStore")
public class Profile implements java.io.Serializable {

	private String userid;
	private String langpref;
	private String favcategory;
	private Integer mylistopt;
	private Integer banneropt;

	public Profile() {
	}

	public Profile(String userid, String langpref) {
		this.userid = userid;
		this.langpref = langpref;
	}

	public Profile(String userid, String langpref, String favcategory,
			Integer mylistopt, Integer banneropt) {
		this.userid = userid;
		this.langpref = langpref;
		this.favcategory = favcategory;
		this.mylistopt = mylistopt;
		this.banneropt = banneropt;
	}

	@Id
	@Column(name = "userid", unique = true, nullable = false, length = 80)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "langpref", nullable = false, length = 80)
	public String getLangpref() {
		return this.langpref;
	}

	public void setLangpref(String langpref) {
		this.langpref = langpref;
	}

	@Column(name = "favcategory", length = 30)
	public String getFavcategory() {
		return this.favcategory;
	}

	public void setFavcategory(String favcategory) {
		this.favcategory = favcategory;
	}

	@Column(name = "mylistopt")
	public Integer getMylistopt() {
		return this.mylistopt;
	}

	public void setMylistopt(Integer mylistopt) {
		this.mylistopt = mylistopt;
	}

	@Column(name = "banneropt")
	public Integer getBanneropt() {
		return this.banneropt;
	}

	public void setBanneropt(Integer banneropt) {
		this.banneropt = banneropt;
	}

	@Override
	public String toString() {
		return "Profile [userid=" + userid + ", langpref=" + langpref
				+ ", favcategory=" + favcategory + ", mylistopt=" + mylistopt
				+ ", banneropt=" + banneropt + "]";
	}
}
