package com.clps.vo;

// Generated 2018-1-12 9:45:46 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sequence generated by hbm2java
 */
@Entity
@Table(name = "sequence", catalog = "jpetStore")
public class Sequence implements java.io.Serializable {

	private String name;
	private int nextid;

	public Sequence() {
	}

	public Sequence(String name, int nextid) {
		this.name = name;
		this.nextid = nextid;
	}

	@Id
	@Column(name = "name", unique = true, nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "nextid", nullable = false)
	public int getNextid() {
		return this.nextid;
	}

	public void setNextid(int nextid) {
		this.nextid = nextid;
	}

}
